@startuml
!define AWS https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v14.0/dist
!include AWS/AWSCommon.puml
!include AWS/Compute/EC2.puml
!include AWS/Compute/EKS.puml
!include AWS/Database/DynamoDB.puml
!include AWS/Storage/S3.puml

package "AWS Cloud" {
  [EKS Cluster] --> [EC2 Instances]
  [EC2 Instances] --> [DynamoDB]
  [DynamoDB] --> [S3 Bucket]
}
@enduml