"""
Alembic Migration Script Template
=================================

This is the Mako template for generating new migration scripts.
"""

"""Initial schema

Revision ID: 57af38c507fd
Revises: 
Create Date: 2026-01-18 23:54:37.961699+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.models.base import LtreeType

# revision identifiers, used by Alembic.
revision: str = "57af38c507fd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("event_category", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_actor_time", "audit_events", ["actor_id", "timestamp"], unique=False)
    op.create_index(
        "ix_audit_details", "audit_events", ["details"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_event_category"), "audit_events", ["event_category"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_organization_id"), "audit_events", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_timestamp"), "audit_events", ["timestamp"], unique=False)
    op.create_index(
        "ix_audit_org_time", "audit_events", ["organization_id", "timestamp"], unique=False
    )
    op.create_index(
        "ix_audit_resource", "audit_events", ["resource_type", "resource_id"], unique=False
    )
    op.create_table(
        "memory_access_log",
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("memory_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("authorized", sa.Boolean(), nullable=False),
        sa.Column("authorization_method", sa.String(length=100), nullable=False),
        sa.Column("denial_reason", sa.Text(), nullable=True),
        sa.Column("access_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.Column("case_id", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_access_denied", "memory_access_log", ["authorized", "timestamp"], unique=False
    )
    op.create_index(
        "ix_access_memory_time", "memory_access_log", ["memory_id", "timestamp"], unique=False
    )
    op.create_index(
        "ix_access_org_time", "memory_access_log", ["organization_id", "timestamp"], unique=False
    )
    op.create_index(
        "ix_access_user_time", "memory_access_log", ["user_id", "timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_memory_access_log_memory_id"), "memory_access_log", ["memory_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_access_log_organization_id"),
        "memory_access_log",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_access_log_timestamp"), "memory_access_log", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_memory_access_log_user_id"), "memory_access_log", ["user_id"], unique=False
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("parent_org_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("clearance_level", sa.Integer(), nullable=False),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "agents",
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("scope", sa.String(length=50), nullable=False),
        sa.Column("scope_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("llm_provider", sa.String(length=50), nullable=False),
        sa.Column("llm_model", sa.String(length=100), nullable=False),
        sa.Column("memory_strategy", sa.String(length=50), nullable=False),
        sa.Column("max_tokens_per_request", sa.Integer(), nullable=False),
        sa.Column("max_memory_results", sa.Integer(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("total_requests", sa.Integer(), nullable=False),
        sa.Column("total_tokens_used", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_organization_id"), "agents", ["organization_id"], unique=False)
    op.create_index("ix_agents_owner", "agents", ["owner_id", "organization_id"], unique=False)
    op.create_index(op.f("ix_agents_owner_id"), "agents", ["owner_id"], unique=False)
    op.create_index(
        "ix_agents_scope", "agents", ["organization_id", "scope", "scope_id"], unique=False
    )
    op.create_table(
        "memory_metadata",
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("owner_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("scope", sa.String(length=50), nullable=False),
        sa.Column("scope_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("memory_type", sa.String(length=50), nullable=False),
        sa.Column("classification", sa.String(length=50), nullable=False),
        sa.Column("required_clearance", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("content_preview", sa.String(length=500), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("entities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("extra_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=True),
        sa.Column("source_id", sa.String(length=255), nullable=True),
        sa.Column("vector_id", sa.String(length=100), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=False),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=True),
        sa.Column("retention_days", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("legal_hold", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_promoted", sa.Boolean(), nullable=False),
        sa.Column("promoted_from_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "classification IN ('public', 'internal', 'confidential', 'restricted')",
            name="ck_memory_classification",
        ),
        sa.CheckConstraint(
            "scope IN ('personal', 'team', 'department', 'division', 'organization', 'global')",
            name="ck_memory_scope",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vector_id"),
    )
    op.create_index(
        "ix_memory_entities", "memory_metadata", ["entities"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        op.f("ix_memory_metadata_content_hash"), "memory_metadata", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_memory_metadata_expires_at"), "memory_metadata", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_memory_metadata_organization_id"),
        "memory_metadata",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_metadata_owner_id"), "memory_metadata", ["owner_id"], unique=False
    )
    op.create_index(
        "ix_memory_org_scope",
        "memory_metadata",
        ["organization_id", "scope", "scope_id"],
        unique=False,
    )
    op.create_index(
        "ix_memory_owner", "memory_metadata", ["organization_id", "owner_id"], unique=False
    )
    op.create_index(
        "ix_memory_tags", "memory_metadata", ["tags"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "organization_hierarchy",
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("node_type", sa.String(length=50), nullable=False),
        sa.Column("path", LtreeType(), nullable=False),
        sa.Column("parent_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["organization_hierarchy.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_org_hierarchy_org_path",
        "organization_hierarchy",
        ["organization_id", "path"],
        unique=False,
    )
    op.create_index(
        "ix_org_hierarchy_parent", "organization_hierarchy", ["parent_id"], unique=False
    )
    op.create_index(
        op.f("ix_organization_hierarchy_organization_id"),
        "organization_hierarchy",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("permissions", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=False)
    op.create_index("ix_roles_name_org", "roles", ["name", "organization_id"], unique=True)
    op.create_index(op.f("ix_roles_organization_id"), "roles", ["organization_id"], unique=False)
    op.create_table(
        "memory_sharing",
        sa.Column("memory_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("share_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("permission", sa.String(length=50), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("shared_by", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("share_reason", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notified_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("permission IN ('read', 'comment', 'edit')", name="ck_share_permission"),
        sa.CheckConstraint(
            "share_type IN ('user', 'team', 'department', 'division', 'organization', 'external')",
            name="ck_share_type",
        ),
        sa.ForeignKeyConstraint(["memory_id"], ["memory_metadata.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["shared_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_sharing_expires_at"), "memory_sharing", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_memory_sharing_memory_id"), "memory_sharing", ["memory_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_sharing_organization_id"),
        "memory_sharing",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_sharing_target_id"), "memory_sharing", ["target_id"], unique=False
    )
    op.create_index("ix_sharing_expires", "memory_sharing", ["expires_at"], unique=False)
    op.create_index(
        "ix_sharing_target", "memory_sharing", ["share_type", "target_id"], unique=False
    )
    op.create_index(
        "ix_sharing_unique", "memory_sharing", ["memory_id", "share_type", "target_id"], unique=True
    )
    op.create_table(
        "teams",
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("hierarchy_node_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hierarchy_node_id"],
            ["organization_hierarchy.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_organization_id"), "teams", ["organization_id"], unique=False)
    op.create_index("ix_teams_slug_org", "teams", ["organization_id", "slug"], unique=True)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("role_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("scope_type", sa.String(length=50), nullable=True),
        sa.Column("scope_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("granted_by", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("grant_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_roles_expires", "user_roles", ["expires_at"], unique=False)
    op.create_index(
        "ix_user_roles_lookup",
        "user_roles",
        ["user_id", "organization_id", "role_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_roles_organization_id"), "user_roles", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False)
    op.create_index(op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False)
    op.create_table(
        "team_members",
        sa.Column("team_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("left_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_team_members_organization_id"), "team_members", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_team_members_team_id"), "team_members", ["team_id"], unique=False)
    op.create_index("ix_team_members_unique", "team_members", ["team_id", "user_id"], unique=True)
    op.create_index(op.f("ix_team_members_user_id"), "team_members", ["user_id"], unique=False)
    op.drop_index("ix_role_assignments_actor_id", table_name="role_assignments", if_exists=True)
    op.drop_index("ix_role_assignments_org_id", table_name="role_assignments", if_exists=True)
    op.drop_index("ix_role_assignments_project_id", table_name="role_assignments", if_exists=True)
    op.execute("DROP TABLE IF EXISTS role_assignments CASCADE")
    op.drop_index("ix_relationships_org_id", table_name="relationships", if_exists=True)
    op.drop_index("ix_relationships_project_id", table_name="relationships", if_exists=True)
    op.drop_index("ix_relationships_source_id", table_name="relationships", if_exists=True)
    op.drop_index("ix_relationships_target_id", table_name="relationships", if_exists=True)
    op.execute("DROP TABLE IF EXISTS relationships CASCADE")
    op.drop_index("ix_memories_content_hash", table_name="memories", if_exists=True)
    op.drop_index("ix_memories_namespace", table_name="memories", if_exists=True)
    op.drop_index("ix_memories_org_id", table_name="memories", if_exists=True)
    op.drop_index("ix_memories_project_id", table_name="memories", if_exists=True)
    op.drop_index("ix_memories_zettel_id", table_name="memories", if_exists=True)
    op.execute("DROP TABLE IF EXISTS memories CASCADE")
    op.drop_index("ix_zettels_org_id", table_name="zettels", if_exists=True)
    op.drop_index("ix_zettels_project_id", table_name="zettels", if_exists=True)
    op.execute("DROP TABLE IF EXISTS zettels CASCADE")
    op.drop_index("ix_collections_org_id", table_name="collections", if_exists=True)
    op.drop_index("ix_collections_parent_id", table_name="collections", if_exists=True)
    op.drop_index("ix_collections_project_id", table_name="collections", if_exists=True)
    op.execute("DROP TABLE IF EXISTS collections CASCADE")
    op.drop_index("ix_project_settings_org_id", table_name="project_settings", if_exists=True)
    op.drop_index("ix_project_settings_project_id", table_name="project_settings", if_exists=True)
    op.execute("DROP TABLE IF EXISTS project_settings CASCADE")
    op.drop_index("ix_budget_events_created_at", table_name="budget_events", if_exists=True)
    op.drop_index("ix_budget_events_namespace", table_name="budget_events", if_exists=True)
    op.drop_index("ix_budget_events_org_id", table_name="budget_events", if_exists=True)
    op.drop_index("ix_budget_events_project_id", table_name="budget_events", if_exists=True)
    op.execute("DROP TABLE IF EXISTS budget_events CASCADE")
    op.execute("DROP TABLE IF EXISTS summary_jobs CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "summary_jobs",
        sa.Column("id", sa.VARCHAR(length=26), autoincrement=False, nullable=False),
        sa.Column("org_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("namespace", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("scope", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("horizon", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("strategy", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "queued_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="summary_jobs_pkey"),
    )
    op.create_table(
        "budget_events",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("namespace", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("amount", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="budget_events_pkey"),
    )
    op.create_index("ix_budget_events_project_id", "budget_events", ["project_id"], unique=False)
    op.create_index("ix_budget_events_org_id", "budget_events", ["org_id"], unique=False)
    op.create_index("ix_budget_events_namespace", "budget_events", ["namespace"], unique=False)
    op.create_index("ix_budget_events_created_at", "budget_events", ["created_at"], unique=False)
    op.create_table(
        "project_settings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("key", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("value", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="project_settings_pkey"),
    )
    op.create_index(
        "ix_project_settings_project_id", "project_settings", ["project_id"], unique=False
    )
    op.create_index("ix_project_settings_org_id", "project_settings", ["org_id"], unique=False)
    op.create_table(
        "collections",
        sa.Column("id", sa.VARCHAR(length=26), autoincrement=False, nullable=False),
        sa.Column("org_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("parent_id", sa.VARCHAR(length=26), autoincrement=False, nullable=True),
        sa.Column(
            "memory_ids", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column(
            "metadata", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="collections_pkey"),
    )
    op.create_index("ix_collections_project_id", "collections", ["project_id"], unique=False)
    op.create_index("ix_collections_parent_id", "collections", ["parent_id"], unique=False)
    op.create_index("ix_collections_org_id", "collections", ["org_id"], unique=False)
    op.create_table(
        "zettels",
        sa.Column("id", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("org_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "tags", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column(
            "backlinks", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="zettels_pkey"),
    )
    op.create_index("ix_zettels_project_id", "zettels", ["project_id"], unique=False)
    op.create_index("ix_zettels_org_id", "zettels", ["org_id"], unique=False)
    op.create_table(
        "memories",
        sa.Column("id", sa.VARCHAR(length=26), autoincrement=False, nullable=False),
        sa.Column("org_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("namespace", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("scope", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("kind", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.Column("zettel_id", sa.VARCHAR(length=32), autoincrement=False, nullable=True),
        sa.Column("content_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column(
            "metadata", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("ttl", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("sensitivity", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "policy_labels",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="memories_pkey"),
    )
    op.create_index("ix_memories_zettel_id", "memories", ["zettel_id"], unique=False)
    op.create_index("ix_memories_project_id", "memories", ["project_id"], unique=False)
    op.create_index("ix_memories_org_id", "memories", ["org_id"], unique=False)
    op.create_index("ix_memories_namespace", "memories", ["namespace"], unique=False)
    op.create_index("ix_memories_content_hash", "memories", ["content_hash"], unique=False)
    op.create_table(
        "relationships",
        sa.Column("id", sa.VARCHAR(length=26), autoincrement=False, nullable=False),
        sa.Column("org_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("source_id", sa.VARCHAR(length=26), autoincrement=False, nullable=False),
        sa.Column("target_id", sa.VARCHAR(length=26), autoincrement=False, nullable=False),
        sa.Column("relation_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("weight", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column(
            "metadata", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="relationships_pkey"),
    )
    op.create_index("ix_relationships_target_id", "relationships", ["target_id"], unique=False)
    op.create_index("ix_relationships_source_id", "relationships", ["source_id"], unique=False)
    op.create_index("ix_relationships_project_id", "relationships", ["project_id"], unique=False)
    op.create_index("ix_relationships_org_id", "relationships", ["org_id"], unique=False)
    op.create_table(
        "role_assignments",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("namespace", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("actor_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="role_assignments_pkey"),
    )
    op.create_index(
        "ix_role_assignments_project_id", "role_assignments", ["project_id"], unique=False
    )
    op.create_index("ix_role_assignments_org_id", "role_assignments", ["org_id"], unique=False)
    op.create_index("ix_role_assignments_actor_id", "role_assignments", ["actor_id"], unique=False)
    op.drop_index(op.f("ix_team_members_user_id"), table_name="team_members")
    op.drop_index("ix_team_members_unique", table_name="team_members")
    op.drop_index(op.f("ix_team_members_team_id"), table_name="team_members")
    op.drop_index(op.f("ix_team_members_organization_id"), table_name="team_members")
    op.drop_table("team_members")
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_organization_id"), table_name="user_roles")
    op.drop_index("ix_user_roles_lookup", table_name="user_roles")
    op.drop_index("ix_user_roles_expires", table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index("ix_teams_slug_org", table_name="teams")
    op.drop_index(op.f("ix_teams_organization_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index("ix_sharing_unique", table_name="memory_sharing")
    op.drop_index("ix_sharing_target", table_name="memory_sharing")
    op.drop_index("ix_sharing_expires", table_name="memory_sharing")
    op.drop_index(op.f("ix_memory_sharing_target_id"), table_name="memory_sharing")
    op.drop_index(op.f("ix_memory_sharing_organization_id"), table_name="memory_sharing")
    op.drop_index(op.f("ix_memory_sharing_memory_id"), table_name="memory_sharing")
    op.drop_index(op.f("ix_memory_sharing_expires_at"), table_name="memory_sharing")
    op.drop_table("memory_sharing")
    op.drop_index(op.f("ix_roles_organization_id"), table_name="roles")
    op.drop_index("ix_roles_name_org", table_name="roles")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(
        op.f("ix_organization_hierarchy_organization_id"), table_name="organization_hierarchy"
    )
    op.drop_index("ix_org_hierarchy_parent", table_name="organization_hierarchy")
    op.drop_index("ix_org_hierarchy_org_path", table_name="organization_hierarchy")
    op.drop_table("organization_hierarchy")
    op.drop_index("ix_memory_tags", table_name="memory_metadata", postgresql_using="gin")
    op.drop_index("ix_memory_owner", table_name="memory_metadata")
    op.drop_index("ix_memory_org_scope", table_name="memory_metadata")
    op.drop_index(op.f("ix_memory_metadata_owner_id"), table_name="memory_metadata")
    op.drop_index(op.f("ix_memory_metadata_organization_id"), table_name="memory_metadata")
    op.drop_index(op.f("ix_memory_metadata_expires_at"), table_name="memory_metadata")
    op.drop_index(op.f("ix_memory_metadata_content_hash"), table_name="memory_metadata")
    op.drop_index("ix_memory_entities", table_name="memory_metadata", postgresql_using="gin")
    op.drop_table("memory_metadata")
    op.drop_index("ix_agents_scope", table_name="agents")
    op.drop_index(op.f("ix_agents_owner_id"), table_name="agents")
    op.drop_index("ix_agents_owner", table_name="agents")
    op.drop_index(op.f("ix_agents_organization_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_memory_access_log_user_id"), table_name="memory_access_log")
    op.drop_index(op.f("ix_memory_access_log_timestamp"), table_name="memory_access_log")
    op.drop_index(op.f("ix_memory_access_log_organization_id"), table_name="memory_access_log")
    op.drop_index(op.f("ix_memory_access_log_memory_id"), table_name="memory_access_log")
    op.drop_index("ix_access_user_time", table_name="memory_access_log")
    op.drop_index("ix_access_org_time", table_name="memory_access_log")
    op.drop_index("ix_access_memory_time", table_name="memory_access_log")
    op.drop_index("ix_access_denied", table_name="memory_access_log")
    op.drop_table("memory_access_log")
    op.drop_index("ix_audit_resource", table_name="audit_events")
    op.drop_index("ix_audit_org_time", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_timestamp"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_organization_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_category"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_index("ix_audit_details", table_name="audit_events", postgresql_using="gin")
    op.drop_index("ix_audit_actor_time", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
